const event_details = {
  "Jhoom Junction": {
    start: "12:30 PM",
    end: "6:00 PM",
    location: "Main Quad",
    category: "GROOVE ARENA",
    day: "Jan 29",
    teamSize: "12-19",
    Participation: "1 team per class",
    imageUrl:
      "https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/00c75b73-0934-4ed4-be2d-a38ea416f81f/91dc1e47-0fb0-4fcd-970f-3dfd14ab403a.png",
    detailsUrl : "/event/interClassDance",  
    },
  "Solo Synergy": {
    start: "11:00 AM",
    end: "2:00 PM",
    location: "Stage 2",
    category: "GROOVE ARENA",
    day: "Jan 31",
    teamSize: 1,
    Participation: "1 student per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/female-dancer-dancing-neon-colored-background_77190-22971.jpg?w=360",
  detailsUrl : "/event/soloDance",},
  "Nrutyanjali": {
    start: "10:00 AM",
    end: "1:00 PM",
    location: "Main Quad",
    category: "GROOVE ARENA",
    day: "Feb 1",
    teamSize: "1-5",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/mesmerizing-indian-classical-dance-performance_670382-122718.jpg",
  detailsUrl : "/event/classicalDance",},
  "The Street Brawl": {
    start: "3:00 PM",
    end: "5:00 PM",
    location: "Stage 2",
    category: "GROOVE ARENA",
    day: "Jan 30",
    teamSize: 1,
    Participation: "1 student per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/vibrant-group-dancers-dynamic-poses-with-colorful-lighting_272375-8948.jpg?w=996",
  detailsUrl : "/event/streetdance",},
  "Step It Up": {
    start: "10:00 AM",
    end: "12:30 PM",
    location: "Main Quad",
    category: "GROOVE ARENA",
    day: "Jan 30",
    teamSize: "6-17",
    Participation: "Multiple teams per college",
    imageUrl:
      "https://img.freepik.com/premium-photo/street-fashion-expressive-movements-hiphop-dance-group-generative-ai_722401-32575.jpg",
  detailsUrl : "/event/interCollegeDance",},
  "Sargam Symphony": {
    start: "10:00 AM",
    end: "1:30 PM",
    location: "Main Quad",
    category: "JAMSPHERE",
    day: "Jan 31",
    teamSize: "2-5",
    Participation: "1 team per class",
    imageUrl:
       "https://img.freepik.com/premium-photo/group-friends-singing-bar_118124-99558.jpg",
  detailsUrl : "/event/groupSinging",},
   "Suron Ke Sikandar": {
    start: "10:00 AM",
    end: "12:00 PM",
    location: "KB Joshi",
    category: "GATHERING HUB",
    day: "Jan 30",
    teamSize: "2-4",
    Participation: "1 team per department",
    imageUrl:
      "https://img.freepik.com/premium-photo/colorful-microphone-black-background-generative-ai_918839-1265.jpg?w=900",
  detailsUrl : "/event/departmentAntakshariStudents",},
  "The Great Faculty Sing-Off": {
    start: "2:00 PM",
    end: "4:00 PM",
    location: "Instru Audi",
    category: "GATHERING HUB",
    day: "Jan 29",
    teamSize: "-",
    Participation: "1 team per department", 
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuS4_IuS-Cf2hoz6fNUsdeUHwhRjwy4IEyzw&s",
  detailsUrl : "/event/departmentAntakshariFaculty",},
  "Cummins Got Latent": {
    start: "12:00 PM",
    end: "2:30 PM",
    location: "Stage 2",
    category: "GATHERING HUB",
    day: "Jan 30",
    teamSize: 1,
    Participation: "1 student per class",
    imageUrl:
      "https://static.vecteezy.com/system/resources/previews/038/498/811/large_2x/ai-generated-magic-background-with-magician-s-hat-free-photo.jpeg",
  detailsUrl : "/event/CumminsGotLatent",},
  "Shantit Kranti": {
    start: "3:00 PM",
    end: "5:00 PM",
    location: "KB Joshi",
    category: "GATHERING HUB",
    day: "Jan 29",
    teamSize: "4-6",
    Participation: "1 team per department",
    imageUrl:
      "https://media.istockphoto.com/id/1494324236/photo/rear-view-of-group-of-children-playing-charades-at-home.jpg?s=612x612&w=0&k=20&c=jyWs-ZeXHCKhf9p3AnEBXFAt3cAAjA06fDOST0dQ2m4=",
  detailsUrl : "/event/DumbCharades",},
  "Kalakar Katta": {
    start: "11:00 AM",
    end: "5:00 PM",
    location: "Instru Quad",
    category: "GATHERING HUB",
    day: "Jan 31",
    teamSize: "-",
    Participation: "-",
    imageUrl:
      "https://img.freepik.com/premium-photo/vibrant-colors-celebrate-beauty-creativity-painted-women-portrait-generated-by-artificial-intelligence_24640-123697.jpg?w=900",
  detailsUrl : "/event/KalakaarKatta",},
  "Escape Room": {
    start: "11:00 AM",
    end: "1:00 PM",
    location: "IT/Mech Bldg",
    category: "GATHERING HUB",
    day: "Jan 31",
    teamSize: 4,
    Participation: "1 team per class (FCFS)",
    imageUrl:
      "https://img.freepik.com/premium-photo/inclusive-pridethemed-escape-room-experience-generative-ai_883586-207229.jpg",
  detailsUrl : "/event/EscapeRoom",},
  "Talaash": {
    start: "10:30 AM",
    end: "12:30 PM",
    location: "Whole Campus",
    category: "GATHERING HUB",
    day: "Feb 1",
    teamSize: 4,
    Participation: "1 team per class",
    imageUrl:
      "https://riddlepedia.com/wp-content/uploads/2024/02/prom-scavenger-hunt-riddles.png",
  detailsUrl : "/event/TreasureHunt",},
  "HauteAura": {
    start: "6:00 PM",
    end: "9:00 PM",
    location: "Samstha Ground",
    category: "HAUTE ROUTE",
    day: "Jan 29",
    teamSize: "18 - 21",
    Participation: "1 team per FINAL YEAR class",
    imageUrl:
      "https://img.freepik.com/premium-photo/high-tech-fashion-show-futuristic-fashion-show_1228145-23396.jpg",
  detailsUrl : "/event/btechfashionShow",},
  "Miss Cummins-Beauty Contest": {
    start: "2:00 PM",
    end: "4:30 PM",
    location: "Main Quad",
    category: "HAUTE ROUTE",
    day: "Jan 31",
    teamSize: 1,
    Participation: "2 student per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/contestants-stunning-evening-gowns-walking-runway-beauty-pageant_1284400-6615.jpg",
  detailsUrl : "/event/missCummins",},
  "Eco Vogue": {
    start: "1:00 PM",
    end: "3:00 PM",
    location: "Main Quad",
    category: "HAUTE ROUTE",
    day: "Jan 30",
    teamSize: "3",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/young-woman-poses-dress-made-from-plastic-bottles_14117-1057472.jpg",
  detailsUrl : "/event/ecoVogue",},
  "Goonj 3.0": {
    start: "2:30 PM",
    end: "4:30 PM",
    location: "Stage 2",
    category: "WORDSMITH’S CORNER",
    day: "Jan 29",
    teamSize: 1,
    Participation: "1 team from per class", 
    imageUrl:
      "https://t3.ftcdn.net/jpg/07/28/02/58/360_F_728025858_THUOpi99IgFjoDdXqFHryVK2u3oMhTbi.jpg",
  detailsUrl : "/event/debateCompetition",},
  "Lights, Quiz, Action!": {
    start: "2:00 PM",
    end: "4:00 PM",
    location: "KB Joshi",
    category: "WORDSMITH’S CORNER",
    day: "Jan 31",
    teamSize: 5,
    Participation: "1 team per class",
    imageUrl:
      "https://t4.ftcdn.net/jpg/06/88/97/09/360_F_688970981_LQ6pXYzZIRyXhpXA44dCUNDt4bjp1bmV.jpg",
  detailsUrl : "/event/quizCompetition",},
  "Spellbound": {
    start: "12:30 PM",
    end: "2:30 PM",
    location: "KB Joshi",
    category: "WORDSMITH’S CORNER",
    day: "Jan 29",
    teamSize: "2-3",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/colorful-3d-letters-scattered-across-vibrant-background-create-playful-atmosphere_93995-69745.jpg",
  detailsUrl : "/event/spellingBee",
},
  "Mic In The Open": {
    start: "3:00 PM",
    end: "5:00 PM",
    location: "Stage 2",
    category: "WORDSMITH’S CORNER",
    day: "Jan 31",
    teamSize: 1,
    Participation: "1 student per class",
    imageUrl:
      "https://media.istockphoto.com/id/1819867493/vector/theater-stage-for-stand-up-show-scene-of-comedy-club-with-microphone-and-curtains.jpg?s=612x612&w=0&k=20&c=67qtxf9Oq3EMEx8doHpK7RNVH-i0zMKa0hm5YaUkEVw=",
  detailsUrl : "/event/openMic",},
  "Taste Wars": {
    start: "10:00 AM",
    end: "2:00 PM",
    location: "Between Main & IT Bldg",
    category: "SAVOURY SYMPHONY",
    day: "Jan 31",
    teamSize: "2-4",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/woman-chefs-hat-preparing-food-vibrant-kitchen_1282444-125893.jpg",
  detailsUrl : "/event/btechfashionShow",},
  "Kicks & Dyes Showdown": {
    start: "12:30 PM",
    end: "2:30 PM",
    location: "Instru Quad",
    category: "ARTISCOPE",
    day: "Jan 29",
    teamSize: "1-2",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/colorful-abstract-design-tshirt_885831-204800.jpg?w=360",
  detailsUrl : "/event/tShirtSneakerCompetition",},
  "Hands On Henna": {
    start: "3:30 PM",
    end: "5:30 PM",
    location: "Mech Circle",
    category: "ARTISCOPE",
    day: "Jan 29",
    teamSize: "1-2",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/henna-mehndi-diwali-background_1278458-10458.jpg",
  detailsUrl : "/event/mehendiCompetition",},
  "Bincredible": {
    start: "1:00 PM",
    end: "3:00 PM",
    location: "Mech Circle",
    category: "ARTISCOPE",
    day: "Feb 1",
    teamSize: "1-2",
    Participation: "1 team per class",
    imageUrl:
      "https://www.causeartist.com/content/images/wp-content/uploads/2020/09/jason-mercier-artactivist-collages-celebrities-waste.jpg",
  detailsUrl : "/event/bestOutOfWaste",},
  "Art-a-thon": {
    start: "2:30 PM",
    end: "4:30 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Jan 31",
    teamSize: "3",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-psd/black-white-drawing-space-ship-with-drawing-space-ship-it_985204-92482.jpg?w=740",
  detailsUrl : "/event/artRelay",},
  "Sketch Sphere": {
    start: "12:30 PM",
    end: "2:00 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Jan 29",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTleWGBIC5UaO2WGwILJCA3g0k6qsXRiWzD5A&s",
  detailsUrl : "/event/sketching",},
  "Doodle Express": {
    start: "12:30 PM",
    end: "2:00 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Jan 30",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://i.pinimg.com/originals/ea/f5/e0/eaf5e00b723dfccf338d1500b1563b8a.jpg",
  detailsUrl : "/event/doodling",},
  "Faces In Focus": {
    start: "10:00 AM",
    end: "12:00 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Jan 30",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP-YwgsqrXbo6If9EgOH7olOylZMrA3hWnjt3IGZswTWDl3JvFsi1ZRQLX14enr9RXoX8&usqp=CAU",
  detailsUrl : "/event/portrait",},
  "Color Combat": {
    start: "2:30 PM",
    end: "4:30 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Jan 29",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0625/3818/6989/files/2_5acf9bab-5dd3-4e04-b42c-d4985ccda17b.jpg?v=1676615530",
  detailsUrl : "/event/painting",},
  "Cosmetic Clash": {
    start: "11:00 AM",
    end: "1:00 PM",
    location: "Instru Garden/Mech Circle",
    category: "ARTISCOPE",
    day: "Jan 31",
    teamSize: "2",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/woman-with-glitter-her-face_118124-201219.jpg",
  detailsUrl : "/event/makeup",},
  "Rangoli-the-vibes": {
    start: "12:00 PM",
    end: "3:00 PM",
    location: "Between Main & IT Bldg",
    category: "ARTISCOPE",
    day: "Feb 1",
    teamSize: "2",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/flower-rangoli-diwali-pongal-made-using-marigold-zendu-flowers-ai-generated_852336-18750.jpg",
  detailsUrl : "/event/rangoli",},
  "The Drama Premiere League": {
    start: "1:00 PM",
    end: "4:30 PM",
    location: "Main Quad",
    category: "THEATRICAL TAPESTRY",
    day: "Feb 1",
    teamSize: "8-13",
    Participation: "20 teams (FCFS)",
    imageUrl:
      "https://img.freepik.com/free-photo/smiling-female-mime-artist-looking-male-mime-artist-peeking-from-curtain_23-2147891614.jpg?t=st=1736355391~exp=1736358991~hmac=ec4c063f23551df45c258cfe81eb7be1375166e53580f9e7644c7eb911910cb0&w=900",
  detailsUrl : "/event/classDrama",},
  "Nazariya": {
    start: "12:00 PM",
    end: "4:00 PM",
    location: "Stage 2",
    category: "THEATRICAL TAPESTRY",
    day: "Feb 1",
    teamSize: "8-20",
    Participation: "-",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnZBdkv7LRq1Q0jsTs2Sz3karz8_TvpYHZlTwJEefntYq_mem1p8_r70ds1jDCIc4e4_o&usqp=CAU",
  detailsUrl : "/event/interCollegeNukkad",},
  "Djembe": {
    start: "12:00 PM",
    end: "2:00 PM",
    location: "Stage 2",
    category: "SKILL LAB",
    day: "Jan 29",
    teamSize: "-",
    Participation: "-",
  imageUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/036/050/173/small/ai-generated-colorful-bongo-drums-on-a-table-photo.jpg",
  detailsUrl : "/event/djembe",
},
  "Ukulele Unplugged": {
    start: "(Day1) 12:30 PM - 4:30 PM",
    end: "(Day2) 10:00 AM - 2:00 PM",
    location: "IT Bulg",
    category: "SKILL LAB",
    day: "Jan 30, Jan 31",
    teamSize: "-",
    Participation: "-",
    imageUrl:
      "https://img.freepik.com/premium-vector/abstract-playing-guitar-colorful-watercolor-painting-background_1278344-3645.jpg",
  detailsUrl : "/event/ukulele",},
  "Texture Moon Painting": {
    start: "12:30 PM",
    end: "2:30 PM",
    location: "Mech Bldg",
    category: "SKILL LAB",
    day: "Jan 30",
    teamSize: "-",
    Participation: "-",
    imageUrl:
      "https://img.freepik.com/premium-photo/mystical-encounter-saturn-s-moon-mimas-impasto-reverie_983420-184246.jpg",
  detailsUrl : "/event/textureMoon",},
  "Fluid Art Frenzy": {
    start: "12:00 PM",
    end: "2:00 PM",
    location: "Mech Bldg",
    category: "SKILL LAB",
    day: "Jan 31",
    teamSize: "-",
    Participation: "-",
    imageUrl:
      "https://u.bluet.hm/s/h/thumbnail/295/852/eyJpZCI6InVwbG9hZHMvbGlzdGluZy8zMTQxMzQvcGF1bC1tb29yZS1saXN0aW5nLWJsdWV0aHVtYi0yNDNkLmpwZyIsInN0b3JhZ2UiOiJzdG9yZSIsIm1ldGFkYXRhIjp7ImZpbGVuYW1lIjoicGF1bC1tb29yZS1saXN0aW5nLWJsdWV0aHVtYi0yNDNkLmpwZyIsIm1pbWVfdHlwZSI6bnVsbH19?signature=b2e2ed7dfbfc9baa2fa85b51aecc62777f42268b5e461edbc186d35c53e7860f",
  detailsUrl : "/event/fluidArt",},
  "Punch Needle": {
    start: "12:00 PM",
    end: "2:00 PM",
    location: "Instru Quad",
    category: "SKILL LAB",
    day: "Feb 1",
    teamSize: "-",
    Participation: "-",
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0835/4333/files/Loopy_Wool_Using_AI_to_design_rug_hooking_projects_flower_www.loopysupply.com_fiber_art_cutting_strips_in_two_600x600.jpg?v=1679600178",
  detailsUrl : "/event/punchNeedle",},
  "AD-O-MANIA": {
    start: "",
    end: "",
    location: "Online",
    category: "THE DIGITAL STAGE",
    day: "",
    teamSize: "4-6",
    Participation: "1 team per class",
    imageUrl:
      "https://491a25fa.delivery.rocketcdn.me/wp-content/uploads/2023/11/Boost-Your-Construction-Business-Discover-the-Best-Places-to-Advertise.jpg",
  detailsUrl : "/event/adOMania",},
  "Face The Beat": {
    start: "",
    end: "",
    location: "Online",
    category: "THE DIGITAL STAGE",
    day: "",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://static.wixstatic.com/media/95dc62_f6350456601847699660ed55b26c6463~mv2.jpg/v1/fit/w_2500,h_1330,al_c/95dc62_f6350456601847699660ed55b26c6463~mv2.jpg",
  detailsUrl : "/event/bexpressionDance",},
  "Octopus Race": {
    start: "8:00 AM",
    end: "10:00 AM",
    location: "Samstha Ground",
    category: "JOYLAND",
    day: "Jan 30",
    teamSize: "4",
    Participation: "1 team per class",
    imageUrl:
      "https://www.shutterstock.com/image-photo/red-octopus-260nw-2449167195.jpg",
  detailsUrl : "/event/octopusRace",},
  "Dodgeball In Circle": {
    start: "10:00 AM",
    end: "11:00 AM",
    location: "Samstha Ground",
    category: "JOYLAND",
    day: "Jan 31",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/dodgeball-game-progress-with-players-dodging-throwing-balls_1314467-116358.jpg",
  detailsUrl : "/event/dodgeballInCircle",},
  "Up Down Race": {
    start: "8:00 AM",
    end: "10:00 AM",
    location: "Samstha Ground",
    category: "JOYLAND",
    day: "Jan 31",
    teamSize: "4",
    Participation: "1 team per class",
    imageUrl:
      "https://img.freepik.com/premium-vector/girls-running-race-marathon-cart-event-outdoors_1316704-14111.jpg",
  detailsUrl : "/event/upDownRace",},
  "Cone Rush": {
    start: "10:00 AM",
    end: "11:00 AM",
    location: "Samstha Ground",
    category: "JOYLAND",
    day: "Jan 30",
    teamSize: "1",
    Participation: "1 student per class",
    imageUrl:
      "https://img.freepik.com/premium-photo/group-colorful-cones_1308175-208949.jpg",
  detailsUrl : "/event/coneRush",},
};

export default event_details;
